sudo: required
os:
- linux
language: node_js
node_js:
- '8'
before_install:
- npm install -g npm@latest
install:
- npm ci
before_script:
- npm run build
script:
- npm run lint
- npm run test
after_success: npm run coverage
